version: "3.9"
services:
  mysql:
    image: mysql:latest
    ports: 
      - "3406:3406"
    container_name: my-mysql
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=mysql
       - MYSQL_PASSWORD=mysql
       - MYSQL_DATABASE=dbmysql
       - MYSQL_ALLOW_EMPTY_PASSWORD=mysql
       - MYSQL_RANDOM_ROOT_PASSWORD=mysql

  exampleini:
    image: teste_exemplo
    container_name: "finale_test"
    volumes:
      - .:/flask-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql